# IPEDS DATA FINALIZATION FOR EACH TABLE

## S2023_IS

In [ ]:
import pandas as pd

df1 = pd.read_csv("S2023_IS_sorted_decimal.csv")
df1.head(10)

,UNITID,SISCAT,FACSTAT,ARANK,HRTOTLT,HRTOTLM,HRTOTLW,HRAIANT,HRAIANM,HRAIANW,...,HRUNKNT,HRUNKNM,HRUNKNW,HRNRALT,HRNRALM,HRNRALW,PRFPERCW,BKAAPERCW,HISPERCW,AISAPERCW
0,100654,101,10,1,40,31,9,0,0,0,...,0,0,0,0,0,0,0.225000,0.125000,0.000000,0.025000
1,100654,102,10,2,53,31,22,0,0,0,...,1,1,0,0,0,0,0.415094,0.245283,0.000000,0.113208
2,100654,200,20,0,73,53,20,0,0,0,...,0,0,0,0,0,0,0.273973,0.178082,0.000000,0.068493
3,100654,201,20,1,36,29,7,0,0,0,...,0,0,0,0,0,0,0.194444,0.138889,0.000000,0.027778
4,100654,202,20,2,29,19,10,0,0,0,...,0,0,0,0,0,0,0.344828,0.241379,0.000000,0.103448
5,100654,203,20,3,8,5,3,0,0,0,...,0,0,0,0,0,0,0.375000,0.125000,0.000000,0.125000
6,100663,201,20,1,616,411,205,1,1,0,...,0,0,0,0,0,0,0.332792,0.021104,0.004870,0.053571
7,100663,200,20,0,904,576,328,1,1,0,...,0,0,0,0,0,0,0.362832,0.027655,0.005531,0.055310
8,100663,202,20,2,288,165,123,0,0,0,...,0,0,0,0,0,0,0.427083,0.041667,0.006944,0.059028
9,100663,101,10,1,787,512,275,1,1,0,...,1,0,1,1,1,0,0.349428,0.021601,0.006353,0.054638

In [ ]:
filter_values = [101, 102, 200]
filtered_df = df1[df1['SISCAT'].isin(filter_values)]
filtered_df.head(10)

,UNITID,SISCAT,FACSTAT,ARANK,HRTOTLT,HRTOTLM,HRTOTLW,HRAIANT,HRAIANM,HRAIANW,...,HRUNKNT,HRUNKNM,HRUNKNW,HRNRALT,HRNRALM,HRNRALW,PRFPERCW,BKAAPERCW,HISPERCW,AISAPERCW
0,100654,101,10,1,40,31,9,0,0,0,...,0,0,0,0,0,0,0.225000,0.125000,0.000000,0.025000
1,100654,102,10,2,53,31,22,0,0,0,...,1,1,0,0,0,0,0.415094,0.245283,0.000000,0.113208
2,100654,200,20,0,73,53,20,0,0,0,...,0,0,0,0,0,0,0.273973,0.178082,0.000000,0.068493
7,100663,200,20,0,904,576,328,1,1,0,...,0,0,0,0,0,0,0.362832,0.027655,0.005531,0.055310
9,100663,101,10,1,787,512,275,1,1,0,...,1,0,1,1,1,0,0.349428,0.021601,0.006353,0.054638
10,100663,102,10,2,732,406,326,1,0,1,...,1,1,0,8,4,4,0.445355,0.047814,0.015027,0.077869
11,100690,101,10,1,14,12,2,0,0,0,...,0,0,0,0,0,0,0.142857,0.000000,0.000000,0.000000
12,100690,102,10,2,7,5,2,0,0,0,...,0,0,0,0,0,0,0.285714,0.142857,0.000000,0.000000
13,100706,101,10,1,75,61,14,1,0,1,...,0,0,0,0,0,0,0.186667,0.013333,0.000000,0.040000
14,100706,102,10,2,87,56,31,0,0,0,...,0,0,0,2,2,0,0.356322,0.022989,0.011494,0.080460

In [ ]:
# Drop irrelevant columns
filtered_df = filtered_df[['UNITID', 'SISCAT', 'HRTOTLT', 'HRTOTLM',
                           'HRTOTLW', 'PRFPERCW', 'BKAAPERCW', 'HISPERCW',
                           'AISAPERCW']]
filtered_df.head(10)

,UNITID,SISCAT,HRTOTLT,HRTOTLM,HRTOTLW,PRFPERCW,BKAAPERCW,HISPERCW,AISAPERCW
0,100654,101,40,31,9,0.225000,0.125000,0.000000,0.025000
1,100654,102,53,31,22,0.415094,0.245283,0.000000,0.113208
2,100654,200,73,53,20,0.273973,0.178082,0.000000,0.068493
7,100663,200,904,576,328,0.362832,0.027655,0.005531,0.055310
9,100663,101,787,512,275,0.349428,0.021601,0.006353,0.054638
10,100663,102,732,406,326,0.445355,0.047814,0.015027,0.077869
11,100690,101,14,12,2,0.142857,0.000000,0.000000,0.000000
12,100690,102,7,5,2,0.285714,0.142857,0.000000,0.000000
13,100706,101,75,61,14,0.186667,0.013333,0.000000,0.040000
14,100706,102,87,56,31,0.356322,0.022989,0.011494,0.080460

In [ ]:
filtered_df.to_csv('S2023_IS_final_decimal.csv', index=False)

## S2023_OC

In [ ]:
df2 = pd.read_csv("S2023_OC_sorted_decimal.csv")
df2.head(10)

,UNITID,OCCUPCAT,HRTOTLT,HRTOTLM,HRTOTLW,HRAIANT,HRAIANM,HRAIANW,HRASIAT,HRASIAM,...,HRUNKNW,HRNRALT,HRNRALM,HRNRALW,BLKPERC,HISPPERC,ASIAPERC,AVGBLKPERC,AVGHISPPERC,AVGASIAPERC
0,100654,100,566,204,362,4,1,3,11,4,...,2,0,0,0,0.874558,0.000000,0.019435,0.13,0.12,0.08
1,100663,100,7432,2371,5061,10,5,5,456,172,...,101,472,242,230,0.311760,0.022067,0.061356,0.13,0.12,0.08
2,100690,100,31,14,17,0,0,0,0,0,...,0,0,0,0,0.096774,0.000000,0.000000,0.13,0.12,0.08
3,100706,100,1055,490,565,11,4,7,37,14,...,0,37,28,9,0.120379,0.022749,0.035071,0.13,0.12,0.08
4,100724,100,571,239,332,0,0,0,10,8,...,7,0,0,0,0.872154,0.003503,0.017513,0.13,0.12,0.08
5,100733,100,98,34,64,0,0,0,3,0,...,0,0,0,0,0.112245,0.020408,0.030612,0.13,0.12,0.08
6,100751,100,4988,1874,3114,4,0,4,97,40,...,2,92,61,31,0.213512,0.021852,0.019447,0.13,0.12,0.08
7,100760,100,116,37,79,0,0,0,0,0,...,0,0,0,0,0.267241,0.008621,0.000000,0.13,0.12,0.08
8,100812,100,194,67,127,2,0,2,3,1,...,0,0,0,0,0.113402,0.015464,0.015464,0.13,0.12,0.08
9,100830,100,464,169,295,2,0,2,19,7,...,19,5,1,4,0.312500,0.006466,0.040948,0.13,0.12,0.08

In [ ]:
# Drop irrelevant columns
filtered_df = df2[['UNITID', 'OCCUPCAT', 'HRTOTLT', 'HRTOTLM',
                           'HRTOTLW', 'BLKPERC', 'HISPPERC', 'ASIAPERC']]
filtered_df.head(10)

   UNITID  OCCUPCAT  HRTOTLT  HRTOTLM  HRTOTLW   BLKPERC  HISPPERC  ASIAPERC
0  100654       100      566      204      362  0.874558  0.000000  0.019435
1  100663       100     7432     2371     5061  0.311760  0.022067  0.061356
2  100690       100       31       14       17  0.096774  0.000000  0.000000
3  100706       100     1055      490      565  0.120379  0.022749  0.035071
4  100724       100      571      239      332  0.872154  0.003503  0.017513
5  100733       100       98       34       64  0.112245  0.020408  0.030612
6  100751       100     4988     1874     3114  0.213512  0.021852  0.019447
7  100760       100      116       37       79  0.267241  0.008621  0.000000
8  100812       100      194       67      127  0.113402  0.015464  0.015464
9  100830       100      464      169      295  0.312500  0.006466  0.040948

In [ ]:
filtered_df.to_csv('S2023_OC_final_decimal.csv', index=False)

## C2023_B

In [ ]:
df3 = pd.read_csv("C2023_B.csv")
df3.head(10)

,UNITID,CSTOTLT,CSTOTLM,CSTOTLW,CSAIANT,CSAIANM,CSAIANW,CSASIAT,CSASIAM,CSASIAW,...,CSGUUGUN,CSGUUGAG,CSGUUGTT,CSGUGUN,CSGUGAG,CSGUGTOT,CSGUTOTUN,CSGUTOTAG,CSGUTOT,CSGUKN
0,100654,729,241,488,3,0,3,2,1,1,...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN
1,100663,6356,2273,4083,12,3,9,408,157,251,...,2,NaN,2.0,0,NaN,0.0,2,NaN,2.0,6354.0
2,100690,171,77,94,0,0,0,0,0,0,...,0,NaN,0.0,0,NaN,0.0,0,NaN,0.0,171.0
3,100706,2288,1202,1086,18,8,10,89,45,44,...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN
4,100724,598,202,396,1,0,1,2,1,1,...,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,598.0
5,100751,8929,3573,5356,36,12,24,135,47,88,...,0,NaN,0.0,0,NaN,0.0,0,NaN,0.0,8929.0
6,100760,232,69,163,2,2,0,1,0,1,...,0,NaN,0.0,0,NaN,0.0,0,NaN,0.0,232.0
7,100812,837,254,583,9,2,7,6,2,4,...,0,NaN,0.0,0,NaN,0.0,0,NaN,0.0,837.0
8,100830,1256,538,718,4,0,4,25,12,13,...,0,NaN,0.0,0,NaN,0.0,0,NaN,0.0,1256.0
9,100858,7764,3769,3995,22,12,10,198,97,101,...,0,NaN,0.0,0,NaN,0.0,0,NaN,0.0,7764.0

In [ ]:
df3 = df3[['UNITID', 'CSTOTLT']]
df3.head(10)

   UNITID  CSTOTLT
0  100654      729
1  100663     6356
2  100690      171
3  100706     2288
4  100724      598
5  100751     8929
6  100760      232
7  100812      837
8  100830     1256
9  100858     7764

In [ ]:
df3.to_csv('C2023_B_final.csv', index=False)

## EF2023

In [ ]:
df4 = pd.read_csv("EF2023.csv")
df4.head(10)

,UNITID,EFLEVEL,EFTOTAL,EFMEN,EFWOM,EFFT,EFFTMEN,EFFTWOM,EFPT,EFPTMEN,EFPTWOM
0,100654,10,6614,2671,3943,5660.0,2282.0,3378.0,954.0,389.0,565.0
1,100654,20,5845,2417,3428,5221.0,2142.0,3079.0,624.0,275.0,349.0
2,100654,30,5726,2389,3337,5219.0,2142.0,3077.0,507.0,247.0,260.0
3,100654,31,1990,816,1174,1976.0,808.0,1168.0,14.0,8.0,6.0
4,100654,34,3736,1573,2163,3243.0,1334.0,1909.0,493.0,239.0,254.0
5,100654,35,280,132,148,246.0,115.0,131.0,34.0,17.0,17.0
6,100654,36,3456,1441,2015,2997.0,1219.0,1778.0,459.0,222.0,237.0
7,100654,40,119,28,91,2.0,0.0,2.0,117.0,28.0,89.0
8,100654,50,769,254,515,439.0,140.0,299.0,330.0,114.0,216.0
9,100663,10,21160,7803,13357,14815.0,5616.0,9199.0,6345.0,2187.0,4158.0

In [ ]:
filter_values = [10]
df4 = df4[df4['EFLEVEL'].isin(filter_values)]

df4.head(10)

,UNITID,EFLEVEL,EFTOTAL,EFMEN,EFWOM,EFFT,EFFTMEN,EFFTWOM,EFPT,EFPTMEN,EFPTWOM
0,100654,10,6614,2671,3943,5660.0,2282.0,3378.0,954.0,389.0,565.0
9,100663,10,21160,7803,13357,14815.0,5616.0,9199.0,6345.0,2187.0,4158.0
18,100690,10,636,275,361,261.0,116.0,145.0,375.0,159.0,216.0
25,100706,10,8743,5178,3565,6275.0,3825.0,2450.0,2468.0,1353.0,1115.0
34,100724,10,3870,1373,2497,3337.0,1190.0,2147.0,533.0,183.0,350.0
42,100751,10,39622,16941,22681,33663.0,14709.0,18954.0,5959.0,2232.0,3727.0
51,100760,10,1910,771,1139,561.0,250.0,311.0,1349.0,521.0,828.0
59,100812,10,2955,900,2055,1184.0,318.0,866.0,1771.0,582.0,1189.0
67,100830,10,5189,2114,3075,3233.0,1306.0,1927.0,1956.0,808.0,1148.0
76,100858,10,33015,16283,16732,27618.0,13411.0,14207.0,5397.0,2872.0,2525.0

In [ ]:
df4 = df4[['UNITID', 'EFLEVEL', 'EFTOTAL']]
df4.head(10)

    UNITID  EFLEVEL  EFTOTAL
0   100654       10     6614
9   100663       10    21160
18  100690       10      636
25  100706       10     8743
34  100724       10     3870
42  100751       10    39622
51  100760       10     1910
59  100812       10     2955
67  100830       10     5189
76  100858       10    33015

In [ ]:
df4.to_csv('EF2023_final.csv', index=False)