# IPEDS LEADERSHIP DATA PREPROCESSING

In [ ]:
import pandas as pd

df1 = pd.read_csv("S2023_IS.csv")
df1.head(10)

,UNITID,SISCAT,FACSTAT,ARANK,HRTOTLT,HRTOTLM,HRTOTLW,HRAIANT,HRAIANM,HRAIANW,...,HRWHITW,HR2MORT,HR2MORM,HR2MORW,HRUNKNT,HRUNKNM,HRUNKNW,HRNRALT,HRNRALM,HRNRALW
0,100654,1,0,0,266,139,127,0,0,0,...,2,46,21,25,3,2,1,0,0,0
1,100654,100,10,0,261,135,126,0,0,0,...,2,46,21,25,3,2,1,0,0,0
2,100654,101,10,1,40,31,9,0,0,0,...,0,4,1,3,0,0,0,0,0,0
3,100654,102,10,2,53,31,22,0,0,0,...,0,5,2,3,1,1,0,0,0,0
4,100654,103,10,3,115,60,55,0,0,0,...,1,27,15,12,0,0,0,0,0,0
5,100654,104,10,4,53,13,40,0,0,0,...,1,10,3,7,2,1,1,0,0,0
6,100654,200,20,0,73,53,20,0,0,0,...,0,5,3,2,0,0,0,0,0,0
7,100654,201,20,1,36,29,7,0,0,0,...,0,2,1,1,0,0,0,0,0,0
8,100654,202,20,2,29,19,10,0,0,0,...,0,1,1,0,0,0,0,0,0,0
9,100654,203,20,3,8,5,3,0,0,0,...,0,2,1,1,0,0,0,0,0,0

In [ ]:
# Filter rows where the 'SISCAT' column has specific values (prof, associate prof, tenured)
filter_values = [101, 102, 200, 201, 202, 203]
filtered_df = df1[df1['SISCAT'].isin(filter_values)]

# Sort the filtered data by the 'UNITID' column in ascending order
sorted_df = filtered_df.sort_values(by='UNITID', ascending=True)

# Display the result
sorted_df.head(10)

,UNITID,SISCAT,FACSTAT,ARANK,HRTOTLT,HRTOTLM,HRTOTLW,HRAIANT,HRAIANM,HRAIANW,...,HRWHITW,HR2MORT,HR2MORM,HR2MORW,HRUNKNT,HRUNKNM,HRUNKNW,HRNRALT,HRNRALM,HRNRALW
2,100654,101,10,1,40,31,9,0,0,0,...,0,4,1,3,0,0,0,0,0,0
3,100654,102,10,2,53,31,22,0,0,0,...,0,5,2,3,1,1,0,0,0,0
6,100654,200,20,0,73,53,20,0,0,0,...,0,5,3,2,0,0,0,0,0,0
7,100654,201,20,1,36,29,7,0,0,0,...,0,2,1,1,0,0,0,0,0,0
8,100654,202,20,2,29,19,10,0,0,0,...,0,1,1,0,0,0,0,0,0,0
9,100654,203,20,3,8,5,3,0,0,0,...,0,2,1,1,0,0,0,0,0,0
32,100663,201,20,1,616,411,205,1,1,0,...,155,2,1,1,0,0,0,0,0,0
31,100663,200,20,0,904,576,328,1,1,0,...,246,4,2,2,0,0,0,0,0,0
33,100663,202,20,2,288,165,123,0,0,0,...,91,2,1,1,0,0,0,0,0,0
27,100663,101,10,1,787,512,275,1,1,0,...,208,2,1,1,1,0,1,1,1,0

In [ ]:
sorted_df.to_csv('S2023_IS_sorted.csv', index=False)

# IPEDS DIVERSITY DATA PREPROCESSING

In [ ]:
df2 = pd.read_csv("S2023_OC.csv")
df2.head(20)

,UNITID,STAFFCAT,FTPT,OCCUPCAT,SABDTYPE,HRTOTLT,HRTOTLM,HRTOTLW,HRAIANT,HRAIANM,...,HRWHITW,HR2MORT,HR2MORM,HR2MORW,HRUNKNT,HRUNKNM,HRUNKNW,HRNRALT,HRNRALM,HRNRALW
0,100654,1100,1,100,-2,1008,432,576,4,1,...,3,134,66,68,10,7,3,0,0,0
1,100654,1200,1,200,-2,384,190,194,1,1,...,2,75,38,37,3,2,1,0,0,0
2,100654,1210,1,210,-2,379,188,191,0,0,...,2,75,38,37,3,2,1,0,0,0
3,100654,1220,1,220,-2,5,2,3,1,1,...,0,0,0,0,0,0,0,0,0,0
4,100654,1250,1,250,-2,25,4,21,0,0,...,0,3,2,1,1,0,1,0,0,0
5,100654,1260,1,260,-2,7,1,6,0,0,...,0,1,1,0,0,0,0,0,0,0
6,100654,1262,1,262,-2,5,1,4,0,0,...,0,1,1,0,0,0,0,0,0,0
7,100654,1263,1,263,-2,2,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
8,100654,1270,1,270,-2,18,3,15,0,0,...,0,2,1,1,1,0,1,0,0,0
9,100654,1300,1,300,-2,91,42,49,0,0,...,0,4,4,0,1,0,1,0,0,0
10,100654,1310,1,310,-2,23,7,16,0,0,...,0,2,2,0,0,0,0,0,0,0
11,100654,1320,1,320,-2,35,18,17,0,0,...,0,5,2,3,0,0,0,0,0,0
12,100654,1330,1,330,-2,128,61,67,2,0,...,0,15,6,9,0,0,0,0,0,0
13,100654,1340,1,340,-2,4,2,2,0,0,...,0,1,0,1,0,0,0,0,0,0
14,100654,1350,1,350,-2,67,41,26,1,0,...,1,4,2,2,1,1,0,0,0,0
15,100654,1370,1,370,-2,188,27,161,0,0,...,0,17,7,10,0,0,0,0,0,0
16,100663,1100,1,100,-2,11035,4411,6624,21,12,...,3515,143,43,100,152,49,103,615,330,285
17,100663,1200,1,200,-2,3206,1673,1533,9,5,...,1063,32,12,20,4,2,2,143,88,55
18,100663,1210,1,210,-2,3206,1673,1533,9,5,...,1063,32,12,20,4,2,2,143,88,55
19,100663,1250,1,250,-2,532,192,340,0,0,...,198,10,1,9,16,7,9,62,35,27

In [ ]:
# Filter rows where the 'OCCUPCAT' column has specific values (non-teaching staff)
filter_values = [220, 230, 250, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 420, 490]
filtered_df = df2[df2['OCCUPCAT'].isin(filter_values)]

# Sort the filtered data by the 'UNITID' column in ascending order
sorted_df = filtered_df.sort_values(by='UNITID', ascending=True)

# Display the result
sorted_df.head(20)

,UNITID,STAFFCAT,FTPT,OCCUPCAT,SABDTYPE,HRTOTLT,HRTOTLM,HRTOTLW,HRAIANT,HRAIANM,...,HRWHITW,HR2MORT,HR2MORM,HR2MORW,HRUNKNT,HRUNKNM,HRUNKNW,HRNRALT,HRNRALM,HRNRALW
3,100654,1220,1,220,-2,5,2,3,1,1,...,0,0,0,0,0,0,0,0,0,0
4,100654,1250,1,250,-2,25,4,21,0,0,...,0,3,2,1,1,0,1,0,0,0
9,100654,1300,1,300,-2,91,42,49,0,0,...,0,4,4,0,1,0,1,0,0,0
10,100654,1310,1,310,-2,23,7,16,0,0,...,0,2,2,0,0,0,0,0,0,0
11,100654,1320,1,320,-2,35,18,17,0,0,...,0,5,2,3,0,0,0,0,0,0
12,100654,1330,1,330,-2,128,61,67,2,0,...,0,15,6,9,0,0,0,0,0,0
13,100654,1340,1,340,-2,4,2,2,0,0,...,0,1,0,1,0,0,0,0,0,0
14,100654,1350,1,350,-2,67,41,26,1,0,...,1,4,2,2,1,1,0,0,0,0
15,100654,1370,1,370,-2,188,27,161,0,0,...,0,17,7,10,0,0,0,0,0,0
29,100663,1350,1,350,-2,921,348,573,4,3,...,92,16,7,9,17,3,14,18,13,5
28,100663,1340,1,340,-2,606,156,450,1,1,...,295,2,0,2,7,1,6,156,84,72
27,100663,1330,1,330,-2,398,150,248,0,0,...,148,6,4,2,14,8,6,3,0,3
30,100663,1370,1,370,-2,908,125,783,1,0,...,301,12,1,11,32,2,30,7,3,4
25,100663,1310,1,310,-2,1431,295,1136,2,0,...,620,21,2,19,22,7,15,10,1,9
24,100663,1300,1,300,-2,476,214,262,1,0,...,172,6,2,4,9,4,5,1,0,1
19,100663,1250,1,250,-2,532,192,340,0,0,...,198,10,1,9,16,7,9,62,35,27
26,100663,1320,1,320,-2,2160,891,1269,1,1,...,612,31,9,22,26,10,16,215,106,109
34,100690,1250,1,250,-2,8,4,4,0,0,...,4,0,0,0,0,0,0,0,0,0
38,100690,1310,1,310,-2,7,1,6,0,0,...,5,0,0,0,0,0,0,0,0,0
39,100690,1320,1,320,-2,5,4,1,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
# Group by the 'UNITID' column and sum all numerical columns
combined_df = sorted_df.groupby('UNITID', as_index=False).sum()

# Drop irrelevant columns
combined_df = combined_df.drop(columns=['FTPT', 'SABDTYPE', 'STAFFCAT'])

# Set all values in the column 'OCCUPCAT' to 100
combined_df['OCCUPCAT'] = 100

# Display the resulting DataFrame
combined_df.head(20)

,UNITID,OCCUPCAT,HRTOTLT,HRTOTLM,HRTOTLW,HRAIANT,HRAIANM,HRAIANW,HRASIAT,HRASIAM,...,HRWHITW,HR2MORT,HR2MORM,HR2MORW,HRUNKNT,HRUNKNM,HRUNKNW,HRNRALT,HRNRALM,HRNRALW
0,100654,100,566,204,362,4,1,3,11,4,...,1,51,25,26,3,1,2,0,0,0
1,100663,100,7432,2371,5061,10,5,5,456,172,...,2438,104,26,78,143,42,101,472,242,230
2,100690,100,31,14,17,0,0,0,0,0,...,16,0,0,0,0,0,0,0,0,0
3,100706,100,1055,490,565,11,4,7,37,14,...,421,5,3,2,0,0,0,37,28,9
4,100724,100,571,239,332,0,0,0,10,8,...,18,0,0,0,16,9,7,0,0,0
5,100733,100,98,34,64,0,0,0,3,0,...,50,2,1,1,0,0,0,0,0,0
6,100751,100,4988,1874,3114,4,0,4,97,40,...,2161,40,9,31,4,2,2,92,61,31
7,100760,100,116,37,79,0,0,0,0,0,...,52,0,0,0,0,0,0,0,0,0
8,100812,100,194,67,127,2,0,2,3,1,...,106,1,1,0,0,0,0,0,0,0
9,100830,100,464,169,295,2,0,2,19,7,...,155,0,0,0,27,8,19,5,1,4
10,100858,100,4899,1846,3053,12,5,7,109,45,...,2287,62,27,35,44,17,27,171,104,67
11,100937,100,173,81,92,0,0,0,2,0,...,69,0,0,0,2,1,1,0,0,0
12,101028,100,98,36,62,0,0,0,0,0,...,23,0,0,0,0,0,0,0,0,0
13,101116,100,25,11,14,0,0,0,0,0,...,4,0,0,0,0,0,0,0,0,0
14,101143,100,118,45,73,0,0,0,0,0,...,53,3,0,3,0,0,0,0,0,0
15,101161,100,290,103,187,1,0,1,0,0,...,131,3,1,2,12,6,6,0,0,0
16,101189,100,219,98,121,0,0,0,3,3,...,100,3,1,2,0,0,0,0,0,0
17,101240,100,298,104,194,1,0,1,0,0,...,141,8,1,7,2,0,2,0,0,0
18,101277,100,5,0,5,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,0
19,101286,100,205,46,159,0,0,0,1,0,...,98,7,0,7,6,2,4,0,0,0

In [ ]:
# Save the result to a new CSV file
combined_df.to_csv('S2023_OC_sorted.csv', index=False)

# IPEDS POLICY DATA PREPROCESSING

In [ ]:
df3 = pd.read_csv("SAL2023_IS.csv")
df3.head(20)

,UNITID,ARANK,SAINSTT,SAINSTM,SAINSTW,SA_9MCT,SA_9MCM,SA_9MCW,SATOTLT,SATOTLM,...,SA09MAW,SA10MAT,SA10MAM,SA10MAW,SA11MAT,SA11MAM,SA11MAW,SA12MAT,SA12MAM,SA12MAW
0,100654,1,40,31,9,7,7,0,33,24,...,91325.0,NaN,NaN,NaN,NaN,NaN,NaN,135554.0,137632.0,131400.0
1,100654,2,53,31,22,5,3,2,48,28,...,86915.0,NaN,NaN,NaN,NaN,NaN,NaN,111227.0,111227.0,NaN
2,100654,3,115,60,55,6,5,1,109,55,...,73487.0,NaN,NaN,NaN,NaN,NaN,NaN,77837.0,NaN,77837.0
3,100654,4,53,13,40,2,1,1,51,12,...,53911.0,NaN,NaN,NaN,NaN,NaN,NaN,50800.0,50800.0,NaN
4,100654,6,5,4,1,2,1,1,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,100654,7,266,139,127,22,17,5,244,122,...,70552.0,NaN,NaN,NaN,NaN,NaN,NaN,108250.0,109703.0,104619.0
6,100663,1,277,157,120,0,0,0,277,157,...,136967.0,NaN,NaN,NaN,NaN,NaN,NaN,214793.0,215456.0,214237.0
7,100663,2,246,134,112,0,0,0,246,134,...,94905.0,NaN,NaN,NaN,NaN,NaN,NaN,149691.0,149437.0,149909.0
8,100663,3,312,95,217,0,0,0,312,95,...,84416.0,NaN,NaN,NaN,NaN,NaN,NaN,113650.0,117355.0,112518.0
9,100663,4,118,37,81,0,0,0,118,37,...,69825.0,NaN,NaN,NaN,NaN,NaN,NaN,100503.0,104630.0,99634.0
10,100663,7,953,423,530,0,0,0,953,423,...,97770.0,NaN,NaN,NaN,NaN,NaN,NaN,147054.0,162275.0,139398.0
11,100690,1,14,12,2,0,0,0,14,12,...,NaN,29600.0,29600.0,NaN,NaN,NaN,NaN,79783.0,77764.0,90883.0
12,100690,2,7,5,2,0,0,0,7,5,...,NaN,38300.0,38300.0,NaN,NaN,NaN,NaN,57506.0,28708.0,115102.0
13,100690,3,6,5,1,0,0,0,6,5,...,NaN,12050.0,12050.0,NaN,NaN,NaN,NaN,55741.0,48286.0,78108.0
14,100690,4,4,3,1,0,0,0,4,3,...,NaN,11000.0,11000.0,NaN,NaN,NaN,NaN,47058.0,40157.0,60861.0
15,100690,7,31,25,6,0,0,0,31,25,...,NaN,20600.0,20600.0,NaN,NaN,NaN,NaN,67167.0,59770.0,91823.0
16,100706,1,75,61,14,0,0,0,75,61,...,134610.0,NaN,NaN,NaN,NaN,NaN,NaN,173668.0,181144.0,141268.0
17,100706,2,87,56,31,0,0,0,87,56,...,92497.0,NaN,NaN,NaN,NaN,NaN,NaN,105991.0,114640.0,93884.0
18,100706,3,118,52,66,0,0,0,118,52,...,81452.0,NaN,NaN,NaN,NaN,NaN,NaN,100910.0,NaN,100910.0
19,100706,4,13,0,13,0,0,0,13,0,...,72121.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Filter rows where the 'ARANK' column has specific values (non-teaching staff)
filter_values = [7]
filtered_df = df3[df3['ARANK'].isin(filter_values)]

# Sort the filtered data by the 'UNITID' column in ascending order
sorted_df = filtered_df.sort_values(by='UNITID', ascending=True)

# Display the result
sorted_df.head(10)

,UNITID,ARANK,SAINSTT,SAINSTM,SAINSTW,SA_9MCT,SA_9MCM,SA_9MCW,SATOTLT,SATOTLM,...,SA09MAW,SA10MAT,SA10MAM,SA10MAW,SA11MAT,SA11MAM,SA11MAW,SA12MAT,SA12MAM,SA12MAW
5,100654,7,266,139,127,22,17,5,244,122,...,70552.0,NaN,NaN,NaN,NaN,NaN,NaN,108250.0,109703.0,104619.0
10,100663,7,953,423,530,0,0,0,953,423,...,97770.0,NaN,NaN,NaN,NaN,NaN,NaN,147054.0,162275.0,139398.0
15,100690,7,31,25,6,0,0,0,31,25,...,NaN,20600.0,20600.0,NaN,NaN,NaN,NaN,67167.0,59770.0,91823.0
21,100706,7,359,195,164,0,0,0,359,195,...,81094.0,NaN,NaN,NaN,NaN,NaN,NaN,117055.0,139279.0,87051.0
27,100724,7,205,101,104,0,0,0,205,101,...,NaN,80151.0,83604.0,76798.0,NaN,NaN,NaN,NaN,NaN,NaN
32,100751,7,1647,857,790,7,2,5,1640,855,...,89367.0,NaN,NaN,NaN,NaN,NaN,NaN,119349.0,135518.0,107190.0
34,100760,7,49,23,26,0,0,0,49,23,...,64363.0,NaN,NaN,NaN,NaN,NaN,NaN,59761.0,59867.0,59621.0
39,100812,7,88,39,49,0,0,0,88,39,...,82698.0,NaN,NaN,NaN,NaN,NaN,NaN,125066.0,121219.0,128913.0
45,100830,7,229,113,116,0,0,0,229,113,...,72725.0,NaN,NaN,NaN,NaN,NaN,NaN,105372.0,126398.0,92551.0
52,100858,7,1466,850,616,0,0,0,1466,850,...,92141.0,NaN,NaN,NaN,NaN,NaN,NaN,148656.0,164414.0,134301.0

In [ ]:
# Keep only columns useful
sorted_df = sorted_df[['UNITID', 'ARANK', 'SAINSTM', 'SAINSTW', 'SAOUTLM', 'SAOUTLW']]

sorted_df.head()

    UNITID  ARANK  SAINSTM  SAINSTW   SAOUTLM   SAOUTLW
5   100654      7      139      127  10412890   8675484
10  100663      7      423      530  57379658  65638438
15  100690      7       25        6   1298408    550937
21  100706      7      195      164  21688839  13418489
27  100724      7      101      104   8443989   7987039

In [ ]:
sorted_df['AVGSALM'] = sorted_df['SAOUTLM'] / sorted_df['SAINSTM']
sorted_df['AVGSALW'] = sorted_df['SAOUTLW'] / sorted_df['SAINSTW']

sorted_df.head()

,UNITID,ARANK,SAINSTM,SAINSTW,SAOUTLM,SAOUTLW,AVGSALM,AVGSALW
5,100654,7,139,127,10412890,8675484,74912.877698,68310.897638
10,100663,7,423,530,57379658,65638438,135649.309693,123846.109434
15,100690,7,25,6,1298408,550937,51936.320000,91822.833333
21,100706,7,195,164,21688839,13418489,111224.815385,81820.054878
27,100724,7,101,104,8443989,7987039,83603.851485,76798.451923

In [ ]:
sorted_df['AVGSALM'] = sorted_df['AVGSALM'].round(2)
sorted_df['AVGSALW'] = sorted_df['AVGSALW'].round(2)

sorted_df.head()

    UNITID  ARANK  SAINSTM  SAINSTW   SAOUTLM   SAOUTLW    AVGSALM    AVGSALW
5   100654      7      139      127  10412890   8675484   74912.88   68310.90
10  100663      7      423      530  57379658  65638438  135649.31  123846.11
15  100690      7       25        6   1298408    550937   51936.32   91822.83
21  100706      7      195      164  21688839  13418489  111224.82   81820.05
27  100724      7      101      104   8443989   7987039   83603.85   76798.45

In [ ]:
sorted_df.to_csv('SAL2023_IS_sorted.csv', index=False)

# IPEDS DAYCARE DATA PREPROCESSING

In [ ]:
df4 = pd.read_csv("IC2023.csv")
df4.head(10)

,UNITID,PEO1ISTR,PEO2ISTR,PEO3ISTR,PEO4ISTR,PEO5ISTR,PEO6ISTR,PEO7ISTR,CNTLAFFI,PUBPRIME,...,ASSOC5,ASSOC6,SPORT1,CONFNO1,SPORT2,CONFNO2,SPORT3,CONFNO3,SPORT4,CONFNO4
0,100654,0,1,0,0,0,0,0,1,2,...,0,0,1,133,1,133,1,133,1,133
1,100663,0,1,1,0,0,0,0,1,2,...,0,0,1,372,1,372,1,372,1,372
2,100690,0,1,0,0,0,0,0,4,-2,...,0,0,2,-2,2,-2,2,-2,2,-2
3,100706,0,1,1,1,0,0,0,1,2,...,0,0,2,-2,1,146,1,146,1,146
4,100724,1,1,0,0,0,0,1,1,2,...,0,0,1,133,1,133,1,133,1,133
5,100733,1,1,1,1,0,0,0,1,2,...,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2
6,100751,1,1,1,0,0,0,0,1,2,...,0,0,1,130,1,130,1,130,1,130
7,100760,1,1,-2,0,1,0,1,1,2,...,0,0,2,-2,2,-2,2,-2,2,-2
8,100812,0,1,0,0,0,0,0,1,2,...,0,0,2,-2,2,-2,2,-2,2,-2
9,100830,0,1,1,0,0,0,1,1,2,...,0,0,2,-2,1,146,1,146,1,146

In [ ]:
# Filter rows where 'LEVEL' equals 1 and 'CNTLAFFI' is in [1, 3, 4]
filtered_df = df4[(df4['LEVEL3'] == 1) |
 (df4['LEVEL4'] == 1) | (df4['LEVEL5'] == 1) |
 (df4['LEVEL6'] == 1) | (df4['LEVEL7'] == 1) |
 (df4['LEVEL8'] == 1) | (df4['LEVEL17'] == 1) |
 (df4['LEVEL18'] == 1) | (df4['LEVEL19'] == 1)]

filtered_df = filtered_df[(filtered_df['CNTLAFFI'].isin([1, 3, 4]))]

# Display the filtered DataFrame
filtered_df.head(10)

,UNITID,PEO1ISTR,PEO2ISTR,PEO3ISTR,PEO4ISTR,PEO5ISTR,PEO6ISTR,PEO7ISTR,CNTLAFFI,PUBPRIME,...,ASSOC5,ASSOC6,SPORT1,CONFNO1,SPORT2,CONFNO2,SPORT3,CONFNO3,SPORT4,CONFNO4
0,100654,0,1,0,0,0,0,0,1,2,...,0,0,1,133,1,133,1,133,1,133
1,100663,0,1,1,0,0,0,0,1,2,...,0,0,1,372,1,372,1,372,1,372
2,100690,0,1,0,0,0,0,0,4,-2,...,0,0,2,-2,2,-2,2,-2,2,-2
3,100706,0,1,1,1,0,0,0,1,2,...,0,0,2,-2,1,146,1,146,1,146
4,100724,1,1,0,0,0,0,1,1,2,...,0,0,1,133,1,133,1,133,1,133
5,100733,1,1,1,1,0,0,0,1,2,...,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2
6,100751,1,1,1,0,0,0,0,1,2,...,0,0,1,130,1,130,1,130,1,130
7,100760,1,1,-2,0,1,0,1,1,2,...,0,0,2,-2,2,-2,2,-2,2,-2
8,100812,0,1,0,0,0,0,0,1,2,...,0,0,2,-2,2,-2,2,-2,2,-2
9,100830,0,1,1,0,0,0,1,1,2,...,0,0,2,-2,1,146,1,146,1,146

In [ ]:
filtered_df = filtered_df[['UNITID', 'CNTLAFFI', 'LEVEL3', 'LEVEL4',
                           'LEVEL5', 'LEVEL6', 'LEVEL7', 'LEVEL8',
                           'LEVEL17', 'LEVEL18', 'LEVEL19', 'STUSRV8']]

filtered_df.head(10)

,UNITID,CNTLAFFI,LEVEL3,LEVEL4,LEVEL5,LEVEL6,LEVEL7,LEVEL8,LEVEL17,LEVEL18,LEVEL19,STUSRV8
0,100654,1,0,0,1,0,1,1,1,0,0,1
1,100663,1,0,0,1,1,1,1,1,1,0,0
2,100690,4,1,0,1,0,1,0,1,0,0,0
3,100706,1,0,0,1,1,1,1,1,1,0,1
4,100724,1,0,0,1,1,1,1,1,1,0,0
5,100733,1,0,1,1,1,1,1,1,1,0,-2
6,100751,1,0,1,1,1,1,1,1,1,0,1
7,100760,1,1,0,-2,-2,-2,-2,-2,-2,-2,0
8,100812,1,0,0,1,1,1,0,0,0,0,0
9,100830,1,0,0,1,1,1,1,1,1,0,1

In [ ]:
filtered_df.to_csv('IC2023_sorted.csv', index=False)