In [1]:
import pandas as pd

df1 = pd.read_csv("hate_cleaned_202122.csv")
df2 = pd.read_csv("vawa_cleaned_202122.csv")
df1.head()

,INSTNM,City,State,Sector_desc,men_total,women_total,Total,AVG_CRIME
0,A Better U Beauty Barber Academy,Albuquerque,NM,"Private for-profit, less-than 2-year",27.0,11.0,38.0,0.0
1,A T Still University of Health Sciences,Kirksville,MO,"Private nonprofit, 4-year or above",1353.0,2370.0,3723.0,0.0
2,ABC Adult School,Cerritos,CA,"Public, less-than 2-year",41.0,152.0,193.0,0.0
3,ABC Beauty Academy,Richardson,TX,"Private for-profit, less-than 2-year",6.0,58.0,64.0,0.0
4,ABCO Technology,Los Angeles,CA,"Private for-profit, less-than 2-year",107.0,10.0,117.0,0.0

In [2]:
df1.rename(columns={'AVG_CRIME': 'AVGPERY_HATE'}, inplace=True)
df2.rename(columns={'AVG_CRIME': 'AVGPERY_VAWA'}, inplace=True)

In [3]:
df1['PERTHOU_HATE'] = (df1['AVGPERY_HATE'] / df1['Total']) * 1000
df2['PERTHOU_VAWA'] = (df2['AVGPERY_VAWA'] / df2['Total']) * 1000
df2.head()

,INSTNM,City,State,Sector_desc,men_total,women_total,Total,AVGPERY_VAWA,PERTHOU_VAWA
0,a better u beauty barber academy,Albuquerque,NM,"Private for-profit, less-than 2-year",27.0,11.0,38.0,0.000000,0.000000
1,a t still university of health sciences,Kirksville,MO,"Private nonprofit, 4-year or above",1353.0,2370.0,3723.0,2.666667,0.716268
2,aaniiih nakoda college,Harlem,MT,"Public, 4-year or above",48.0,67.0,115.0,0.000000,0.000000
3,abc adult school,Cerritos,CA,"Public, less-than 2-year",41.0,152.0,193.0,0.000000,0.000000
4,abc beauty academy,Richardson,TX,"Private for-profit, less-than 2-year",6.0,58.0,64.0,0.000000,0.000000

In [4]:
df1.shape

(5684, 9)

In [5]:
df2.shape

(5682, 9)

In [7]:
df1['AVGALL_HATE'] = df1['AVGPERY_HATE'].sum() / 5684
df2['AVGALL_VAWA'] = df2['AVGPERY_VAWA'].sum() / 5682
df2.head()

,INSTNM,City,State,Sector_desc,men_total,women_total,Total,AVGPERY_VAWA,PERTHOU_VAWA,AVGALL_VAWA
0,a better u beauty barber academy,Albuquerque,NM,"Private for-profit, less-than 2-year",27.0,11.0,38.0,0.000000,0.000000,1.563241
1,a t still university of health sciences,Kirksville,MO,"Private nonprofit, 4-year or above",1353.0,2370.0,3723.0,2.666667,0.716268,1.563241
2,aaniiih nakoda college,Harlem,MT,"Public, 4-year or above",48.0,67.0,115.0,0.000000,0.000000,1.563241
3,abc adult school,Cerritos,CA,"Public, less-than 2-year",41.0,152.0,193.0,0.000000,0.000000,1.563241
4,abc beauty academy,Richardson,TX,"Private for-profit, less-than 2-year",6.0,58.0,64.0,0.000000,0.000000,1.563241

In [10]:
df1.to_csv('hate_final_202122.csv', index=False)
df2.to_csv('vawa_final_202122.csv', index=False)