In [ ]:
import pandas as pd

merged = pd.read_csv("gf2025.csv")

In [ ]:
duplicated_rows = merged[merged.duplicated(subset='UNITID', keep=False)]
duplicated_rows.head()

,UNITID,INSTNM,EIN,OPEID,IALIAS,ADDR,CITY,STABBR,ZIP,WEBADDR,...,HISPERCW_200,AISAPERCW_101,AISAPERCW_102,AISAPERCW_200,AVGPERY_HATE,PERTHOU_HATE,AVGALL_HATE,AVGPERY_VAWA,PERTHOU_VAWA,AVGALL_VAWA
369,133553,Embry-Riddle Aeronautical University-Daytona B...,590936101,147900,Embry Riddle Aeronautical University-Daytona B...,1 Aerospace Blvd.,Daytona Beach,FL,32114-3900,daytonabeach.erau.edu/,...,0.006579,0.04,0.037037,0.052632,0.0,0,0.075803,2.333333,0.226515225,0.473938
370,133553,Embry-Riddle Aeronautical University-Daytona B...,590936101,147900,Embry Riddle Aeronautical University-Daytona B...,1 Aerospace Blvd.,Daytona Beach,FL,32114-3900,daytonabeach.erau.edu/,...,0.006579,0.04,0.037037,0.052632,0.0,0,0.075803,0.000000,0,0.473938
371,133553,Embry-Riddle Aeronautical University-Daytona B...,590936101,147900,Embry Riddle Aeronautical University-Daytona B...,1 Aerospace Blvd.,Daytona Beach,FL,32114-3900,daytonabeach.erau.edu/,...,0.006579,0.04,0.037037,0.052632,0.0,0,0.075803,2.333333,0.226515225,0.473938
372,133553,Embry-Riddle Aeronautical University-Daytona B...,590936101,147900,Embry Riddle Aeronautical University-Daytona B...,1 Aerospace Blvd.,Daytona Beach,FL,32114-3900,daytonabeach.erau.edu/,...,0.006579,0.04,0.037037,0.052632,0.0,0,0.075803,0.000000,0,0.473938
617,151290,Indiana Institute of Technology,350845258,180500,"Indiana Tech, IIT",1600 E Washington Blvd,Fort Wayne,IN,46803-1228,www.indianatech.edu/,...,0.000000,0.00,0.043478,0.035714,0.0,0,0.075803,1.333333,0.513808606,0.473938

In [ ]:
duplicated_rows.shape

(48, 47)

In [ ]:
duplicated_rows.to_csv("duplicated_rows.csv", index=False)

In [ ]:
merged.shape

(2430, 47)

In [ ]:
merged = merged.drop(duplicated_rows.index)

In [ ]:
merged.shape

(2382, 47)

In [ ]:
# Define the custom aggregation function
def resolve_duplicates(group):
    result = {}
    for col in group.columns:
        if col == 'UNITID':  # Keep UNITID as is
            result[col] = group[col].iloc[0]
        else:
            # Get all non-null values for the column
            non_null_values = group[col].dropna().values
            if len(non_null_values) == 0:
                result[col] = None  # No values
            elif len(non_null_values) == 1:
                result[col] = non_null_values[0]  # One unique value
            else:
                result[col] = non_null_values[-1]  # Latest value
    return pd.Series(result)

In [ ]:
# Group by UNITID and apply the custom aggregation
result_df = duplicated_rows.groupby('UNITID').apply(resolve_duplicates).reset_index(drop=True)

<ipython-input-10-ec90a35408b1>:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result_df = duplicated_rows.groupby('UNITID').apply(resolve_duplicates).reset_index(drop=True)

In [ ]:
result_df.head(10)

,UNITID,INSTNM,EIN,OPEID,IALIAS,ADDR,CITY,STABBR,ZIP,WEBADDR,...,HISPERCW_200,AISAPERCW_101,AISAPERCW_102,AISAPERCW_200,AVGPERY_HATE,PERTHOU_HATE,AVGALL_HATE,AVGPERY_VAWA,PERTHOU_VAWA,AVGALL_VAWA
0,133553,Embry-Riddle Aeronautical University-Daytona B...,590936101,147900,Embry Riddle Aeronautical University-Daytona B...,1 Aerospace Blvd.,Daytona Beach,FL,32114-3900,daytonabeach.erau.edu/,...,0.006579,0.040000,0.037037,0.052632,0.000000,0,0.075803,0.000000,0,0.473938
1,151290,Indiana Institute of Technology,350845258,180500,"Indiana Tech, IIT",1600 E Washington Blvd,Fort Wayne,IN,46803-1228,www.indianatech.edu/,...,0.000000,0.000000,0.043478,0.035714,0.000000,0,0.075803,0.000000,0,0.473938
2,160621,Southern University and A & M College,726000817,202500,Southern University Baton Rouge,"P.O. Box 9374, Harding Blvd",Baton Rouge,LA,70813,www.subr.edu/,...,0.010000,0.046875,0.080000,0.050000,0.000000,0,0.075803,3.666667,0.445741146,0.473938
3,167899,Springfield College,42104329,221100,None,263 Alden St,Springfield,MA,01109-3797,www.springfield.edu/,...,0.000000,0.022222,0.033898,0.025000,0.000000,0,0.075803,0.000000,0,0.473938
4,176947,Central Methodist University-College of Libera...,430654854,245300,CMU - CLAS,411 Central Methodist Square,Fayette,MO,65248-1198,www.centralmethodist.edu/,...,0.000000,0.058824,0.000000,0.035714,0.000000,0,0.075803,0.333333,0.308641975,0.473938
5,210304,Warner Pacific University,930386890,322500,None,2219 SE 68th Ave,Portland,OR,97215,https://www.warnerpacific.edu/,...,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.075803,0.000000,0,0.473938
6,215798,Saint Vincent College,250964126,336800,None,300 Fraser Purchase Rd,Latrobe,PA,15650-2690,https://www.stvincent.edu/,...,0.000000,0.034483,0.000000,0.000000,0.000000,0,0.075803,0.000000,0,0.473938
7,228875,Texas Christian University,750827465,363600,TCU,2800 S University Dr,Fort Worth,TX,76129,https://www.tcu.edu/,...,0.016854,0.032407,0.063636,0.053371,0.666667,0.054319781,0.075803,17.666667,1.439474185,0.473938
8,236133,Northwest University,910615846,378300,None,5520 108th Ave NE,Kirkland,WA,98083-0579,www.northwestu.edu/,...,0.000000,0.181818,0.041667,0.150000,0.000000,0,0.075803,0.000000,0,0.473938
9,426314,Embry-Riddle Aeronautical University-Worldwide,590936101,147900,Embry Riddle Aeronautical University-Worldwide,1 Aerospace Blvd.,Daytona Beach,FL,32114-3900,worldwide.erau.edu/,...,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.075803,0.000000,0,0.473938

In [ ]:
result_df.shape

(12, 47)

In [ ]:
result_df.to_csv("deduplicated_rows.csv", index=False)

In [ ]:
result = pd.concat([merged, result_df], ignore_index=True)
result.shape

(2394, 47)

In [ ]:
result.to_csv("gf2025_final.csv", index=False)

In [ ]:
dup = result[result.duplicated(subset='UNITID', keep=False)]
dup.head()

Empty DataFrame
Columns: [UNITID, INSTNM, EIN, OPEID, IALIAS, ADDR, CITY, STABBR, ZIP, WEBADDR, CSTOTLT, EFTOTAL, CNTLAFFI, STUSRV8, SAINSTM, SAINSTW, SAOUTLM, SAOUTLW, AVGSALM, AVGSALW, AVGALLM, AVGALLW, OCCUPCAT, HRTOTLT, HRTOTLM, HRTOTLW, BLKPERC, HISPPERC, ASIAPERC, PRFPERCW_101, PRFPERCW_102, PRFPERCW_200, BKAAPERCW_101, BKAAPERCW_102, BKAAPERCW_200, HISPERCW_101, HISPERCW_102, HISPERCW_200, AISAPERCW_101, AISAPERCW_102, AISAPERCW_200, AVGPERY_HATE, PERTHOU_HATE, AVGALL_HATE, AVGPERY_VAWA, PERTHOU_VAWA, AVGALL_VAWA]
Index: []

[0 rows x 47 columns]