# IPEDS CSS MERGE

## Merge CSS (hate & vawa)

In [ ]:
import pandas as pd

hate = pd.read_csv("hate_final_202122.csv")
vawa = pd.read_csv("vawa_final_202122.csv")

In [ ]:
css = pd.merge(hate, vawa, on='OPEID', suffixes=('', '_dup'))
css.head()

,INSTNM,OPEID,City,State,Sector_desc,men_total,women_total,Total,AVGPERY_HATE,PERTHOU_HATE,...,INSTNM_dup,City_dup,State_dup,Sector_desc_dup,men_total_dup,women_total_dup,Total_dup,AVGPERY_VAWA,PERTHOU_VAWA,AVGALL_VAWA
0,A Better U Beauty Barber Academy,4283300,Albuquerque,NM,"Private for-profit, less-than 2-year",27.0,11.0,38.0,0.0,0,...,A Better U Beauty Barber Academy,Albuquerque,NM,"Private for-profit, less-than 2-year",27.0,11.0,38.0,0.000000,0,0.473938
1,A T Still University of Health Sciences,247700,Kirksville,MO,"Private nonprofit, 4-year or above",1353.0,2370.0,3723.0,0.0,0,...,A T Still University of Health Sciences,Kirksville,MO,"Private nonprofit, 4-year or above",1353.0,2370.0,3723.0,2.666667,0.716268242,0.473938
2,ABC Adult School,4227000,Cerritos,CA,"Public, less-than 2-year",41.0,152.0,193.0,0.0,0,...,ABC Adult School,Cerritos,CA,"Public, less-than 2-year",41.0,152.0,193.0,0.000000,0,0.473938
3,ABC Beauty Academy,4168800,Richardson,TX,"Private for-profit, less-than 2-year",6.0,58.0,64.0,0.0,0,...,ABC Beauty Academy,Richardson,TX,"Private for-profit, less-than 2-year",6.0,58.0,64.0,0.000000,0,0.473938
4,ABCO Technology,4242600,Los Angeles,CA,"Private for-profit, less-than 2-year",107.0,10.0,117.0,0.0,0,...,ABCO Technology,Los Angeles,CA,"Private for-profit, less-than 2-year",107.0,10.0,117.0,0.000000,0,0.473938

In [ ]:
css.to_csv("css_final_202122.csv", index=False)

## Merge IPEDS & CSS

In [ ]:
css = pd.read_csv("css_final_202122.csv")
ipeds = pd.read_csv("merged_final.csv")

In [ ]:
merged_df = pd.merge(ipeds, css, on='OPEID', how='inner')
merged_df.head(10)

,UNITID,INSTNM,EIN,OPEID,IALIAS,ADDR,CITY,STABBR,ZIP,WEBADDR,...,AVGHISPPERCW_200,AVGASIAPERCW_101,AVGASIAPERCW_102,AVGASIAPERCW_200,AVGPERY_HATE,PERTHOU_HATE,AVGALL_HATE,AVGPERY_VAWA,PERTHOU_VAWA,AVGALL_VAWA
0,100654,Alabama A & M University,636001109,100200,AAMU,4900 Meridian Street,Normal,AL,35762,www.aamu.edu/,...,3%,4%,6%,5%,0.000000,0,0.075803,11.666667,1.942178569,0.473938
1,100663,University of Alabama at Birmingham,636005396,105200,UAB,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,https://www.uab.edu/,...,3%,4%,6%,5%,1.333333,0.061617142,0.075803,48.333333,2.233621393,0.473938
2,100706,University of Alabama in Huntsville,630520830,105500,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,www.uah.edu/,...,3%,4%,6%,5%,0.666667,0.072173505,0.075803,2.333333,0.252607268,0.473938
3,100724,Alabama State University,636001101,100500,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,www.alasu.edu/,...,3%,4%,6%,5%,0.000000,0,0.075803,5.333333,1.393242773,0.473938
4,100751,The University of Alabama,636001138,105100,NaN,739 University Blvd,Tuscaloosa,AL,35487-0100,www.ua.edu/,...,3%,4%,6%,5%,1.333333,0.034502985,0.075803,24.666667,0.638305213,0.473938
5,100760,Central Alabama Community College,631022757,100700,NaN,1675 Cherokee Rd,Alexander City,AL,35010,www.cacc.edu/,...,3%,4%,6%,5%,0.000000,0,0.075803,0.666667,0.375164134,0.473938
6,100812,Athens State University,630701340,100800,NaN,300 N Beaty St,Athens,AL,35611,https://www.athens.edu/,...,3%,4%,6%,5%,0.000000,0,0.075803,0.000000,0,0.473938
7,100830,Auburn University at Montgomery,636000724,831000,AUM||Auburn University at Montgomery|Auburn Mo...,7440 East Drive,Montgomery,AL,36117-3596,www.aum.edu/,...,3%,4%,6%,5%,1.333333,0.26097736,0.075803,8.666667,1.696352841,0.473938
8,100858,Auburn University,636000724,100900,NaN,NaN,Auburn,AL,36849,www.auburn.edu/,...,3%,4%,6%,5%,0.666667,0.020988121,0.075803,50.666667,1.595097175,0.473938
9,100937,Birmingham-Southern College,630708730,101200,BSC,900 Arkadelphia Road,Birmingham,AL,35254,www.bsc.edu/,...,3%,4%,6%,5%,0.000000,0,0.075803,0.666667,0.683760684,0.473938

In [ ]:
merged_df.shape

(2430, 58)

In [ ]:
merged_df.to_csv("merged_ipeds_css.csv", index=False)